from src.games.gen1.base import Gen1GameDefinition
from src.games.gen1.constants import (
    RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    BLUE_JP_SPECIES_NAME_TABLE_OFFSET,
    RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    BLUE_JP_TITLE_SCREEN_FIRST_MON_OFFSET,
    RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    BLUE_JP_TITLE_SCREEN_MON_LIST_OFFSET,
    STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    INTL_STARTING_MONEY_PATCH_OFFSET,
    INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

BLUE_DE = Gen1GameDefinition(
    name="POKéMON BLAUE",
    internal_title="POKEMON BLUE",
    generation=1,
    language_code="D",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0xCB,
    global_checksum=0x2EBC,
    species_name_table_offset=RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x6194,
    starting_money_wram_offset=0xD34C,
    starting_money_routine_offset=0xF876,
    starting_money_middle_byte_offset=0xF87A,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF880,
    starting_pc_item_offset=0x615B,
    player_starter_offsets=[0x1D10E, 0x1D11F, 0x1D130],
    rival_starter_offsets=[0x3A1ED, 0x3A1F0, 0x3A1F3],
    pokedex_owned_wram_offset=0xD2FC,
    show_pokedex_data_routine_offset=0x3E87,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

BLUE_EN = Gen1GameDefinition(
    name="POKéMON BLUE",
    internal_title="POKEMON BLUE",
    generation=1,
    language_code="E",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0xD3,
    global_checksum=0x9D0A,
    species_name_table_offset=RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x616D,
    starting_money_wram_offset=0xD347,
    starting_money_routine_offset=0xF87D,
    starting_money_middle_byte_offset=0xF881,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF887,
    starting_pc_item_offset=0x6134,
    player_starter_offsets=[0x1D10E, 0x1D11F, 0x1D130],
    rival_starter_offsets=[0x3A1E5, 0x3A1E8, 0x3A1EB],
    pokedex_owned_wram_offset=0xD2F7,
    show_pokedex_data_routine_offset=0x3E6D,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

BLUE_ES = Gen1GameDefinition(
    name="POKéMON AZUL",
    internal_title="POKEMON BLUE",
    generation=1,
    language_code="S",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0xCB,
    global_checksum=0x14D7,
    species_name_table_offset=RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x61CC,
    starting_money_wram_offset=0xD34C,
    starting_money_routine_offset=0xF87F,
    starting_money_middle_byte_offset=0xF883,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF889,
    starting_pc_item_offset=0x6193,
    player_starter_offsets=[0x1D10E, 0x1D11F, 0x1D130],
    rival_starter_offsets=[0x3A1F2, 0x3A1F5, 0x3A1F8],
    pokedex_owned_wram_offset=0xD2FC,
    show_pokedex_data_routine_offset=0x3E8C,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

BLUE_FR = Gen1GameDefinition(
    name="POKéMON BLEUE",
    internal_title="POKEMON BLUE",
    generation=1,
    language_code="F",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0xCB,
    global_checksum=0x56A4,
    species_name_table_offset=RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x6208,
    starting_money_wram_offset=0xD34C,
    starting_money_routine_offset=0xF86D,
    starting_money_middle_byte_offset=0xF871,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF877,
    starting_pc_item_offset=0x61CF,
    player_starter_offsets=[0x1D10E, 0x1D11F, 0x1D130],
    rival_starter_offsets=[0x3A1E8, 0x3A1EB, 0x3A1EE],
    pokedex_owned_wram_offset=0xD2FC,
    show_pokedex_data_routine_offset=0x3E8A,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

BLUE_IT = Gen1GameDefinition(
    name="POKéMON BLU",
    internal_title="POKEMON BLUE",
    generation=1,
    language_code="I",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0xCB,
    global_checksum=0x5E9C,
    species_name_table_offset=RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x61CB,
    starting_money_wram_offset=0xD34C,
    starting_money_routine_offset=0xF877,
    starting_money_middle_byte_offset=0xF87B,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF881,
    starting_pc_item_offset=0x6192,
    player_starter_offsets=[0x1D10E, 0x1D11F, 0x1D130],
    rival_starter_offsets=[0x3A20D, 0x3A210, 0x3A213],
    pokedex_owned_wram_offset=0xD2FC,
    show_pokedex_data_routine_offset=0x3E85,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

BLUE_JP = Gen1GameDefinition(
    name="ポケットモンスター 青",
    internal_title="POKEMON BLUE",
    generation=1,
    language_code="J",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0xE5,
    global_checksum=0xDC36,
    species_name_table_offset=BLUE_JP_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=BLUE_JP_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=BLUE_JP_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x60C4,
    starting_money_wram_offset=0xD2CB,
    starting_money_routine_offset=0xFBD1,
    starting_money_middle_byte_offset=0xFBD5,
    starting_money_patch_offset=None,
    starting_money_return_offset=0xFBDB,
    starting_pc_item_offset=0x608B,
    player_starter_offsets=[0x1CBA7, 0x1CBB8, 0x1CBC9],
    rival_starter_offsets=[0x3A556, 0x3A559, 0x3A55C],
    pokedex_owned_wram_offset=0xD27B,
    show_pokedex_data_routine_offset=0x3EB1,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=None,
)

BLUE_VERSIONS = [
    BLUE_DE,
    BLUE_EN,
    BLUE_ES,
    BLUE_FR,
    BLUE_IT,
    BLUE_JP,
]
