from src.games.gen1.base import Gen1GameDefinition
from src.games.gen1.constants import (
    RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    RG_JP_SPECIES_NAME_TABLE_OFFSET,
    RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    RG_JP_TITLE_SCREEN_FIRST_MON_OFFSET,
    RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    RG_JP_TITLE_SCREEN_MON_LIST_OFFSET,
    STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    INTL_STARTING_MONEY_PATCH_OFFSET,
    INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

RED_DE = Gen1GameDefinition(
    name="POKéMON ROTE",
    internal_title="POKEMON RED",
    generation=1,
    language_code="D",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x18,
    global_checksum=0x5CDC,
    species_name_table_offset=RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x6193,
    starting_money_wram_offset=0xD34C,
    starting_money_routine_offset=0xF876,
    starting_money_middle_byte_offset=0xF87A,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF880,
    starting_pc_item_offset=0x615B,
    player_starter_offsets=[0x1D10E, 0x1D11F, 0x1D130],
    rival_starter_offsets=[],
    pokedex_owned_wram_offset=0xD2FC,
    show_pokedex_data_routine_offset=0x3E87,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

RED_EN = Gen1GameDefinition(
    name="POKéMON RED",
    internal_title="POKEMON RED",
    generation=1,
    language_code="E",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x20,
    global_checksum=0x91E6,
    species_name_table_offset=RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x616D,
    starting_money_wram_offset=0xD347,
    starting_money_routine_offset=0xF87D,
    starting_money_middle_byte_offset=0xF881,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF887,
    starting_pc_item_offset=0x6134,
    player_starter_offsets=[0x1D10E, 0x1D11F, 0x1D130],
    rival_starter_offsets=[],
    pokedex_owned_wram_offset=0xD2F7,
    show_pokedex_data_routine_offset=0x3E6D,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

RED_ES = Gen1GameDefinition(
    name="POKéMON ROJA",
    internal_title="POKEMON RED",
    generation=1,
    language_code="S",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x18,
    global_checksum=0x384A,
    species_name_table_offset=RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x61CC,
    starting_money_wram_offset=0xD34C,
    starting_money_routine_offset=0xF87F,
    starting_money_middle_byte_offset=0xF883,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF889,
    starting_pc_item_offset=0x6193,
    player_starter_offsets=[0x1D10E, 0x1D11F, 0x1D130],
    rival_starter_offsets=[],
    pokedex_owned_wram_offset=0xD2FC,
    show_pokedex_data_routine_offset=0x3E8C,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

RED_FR = Gen1GameDefinition(
    name="POKéMON ROUGE",
    internal_title="POKEMON RED",
    generation=1,
    language_code="F",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x18,
    global_checksum=0x7AFC,
    species_name_table_offset=RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x6208,
    starting_money_wram_offset=0xD34C,
    starting_money_routine_offset=0xF86D,
    starting_money_middle_byte_offset=0xF871,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF877,
    starting_pc_item_offset=0x61CF,
    player_starter_offsets=[0x1D10E, 0x1D11F, 0x1D130],
    rival_starter_offsets=[],
    pokedex_owned_wram_offset=0xD2FC,
    show_pokedex_data_routine_offset=0x3E8A,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

RED_IT = Gen1GameDefinition(
    name="POKéMON ROSSA",
    internal_title="POKEMON RED",
    generation=1,
    language_code="I",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x18,
    global_checksum=0x89D2,
    species_name_table_offset=RB_INTL_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RB_INTL_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RB_INTL_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x61CC,
    starting_money_wram_offset=0xD34C,
    starting_money_routine_offset=0xF877,
    starting_money_middle_byte_offset=0xF87B,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF881,
    starting_pc_item_offset=0x6193,
    player_starter_offsets=[0x1D10E, 0x1D11F, 0x1D130],
    rival_starter_offsets=[],
    pokedex_owned_wram_offset=0xD2FC,
    show_pokedex_data_routine_offset=0x3E85,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=INTL_STARTER_DEX_PREVIEW_PATCH_OFFSET,
)

RED_JP_V10 = Gen1GameDefinition(
    name="ポケットモンスター 赤",
    internal_title="POKEMON RED",
    generation=1,
    language_code="J",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x32,
    global_checksum=0xA2C1,
    species_name_table_offset=RG_JP_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RG_JP_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RG_JP_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x5FB1,
    starting_money_wram_offset=0xD2CB,
    starting_money_routine_offset=0xFBC3,
    starting_money_middle_byte_offset=0xFBCA,
    starting_money_patch_offset=0xFBC3,
    starting_pc_item_offset=0x5F78,
    player_starter_offsets=[0x1CBA7, 0x1CBB8, 0x1CBC9],
    rival_starter_offsets=[],
    pokedex_owned_wram_offset=0xD27B,
    show_pokedex_data_routine_offset=0x3E9D,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=None,
)

RED_JP_V11 = Gen1GameDefinition(
    name="ポケットモンスター 赤",
    internal_title="POKEMON RED",
    generation=1,
    language_code="J",
    revision="v1.1",
    version_byte=0x01,
    header_checksum=0x31,
    global_checksum=0xB866,
    species_name_table_offset=RG_JP_SPECIES_NAME_TABLE_OFFSET,
    title_screen_first_mon_offset=RG_JP_TITLE_SCREEN_FIRST_MON_OFFSET,
    title_screen_mon_list_offset=RG_JP_TITLE_SCREEN_MON_LIST_OFFSET,
    intro_mon_offset=0x5F55,
    starting_money_wram_offset=0xD2CB,
    starting_money_routine_offset=0xFBC3,
    starting_money_middle_byte_offset=0xFBCA,
    starting_money_patch_offset=0xFBC3,
    starting_pc_item_offset=0x5F1D,
    player_starter_offsets=[0x1CBA7, 0x1CBB8, 0x1CBC9],
    rival_starter_offsets=[],
    pokedex_owned_wram_offset=0xD27B,
    show_pokedex_data_routine_offset=0x3E8B,
    starter_dex_preview_routine_offset=STARTER_DEX_PREVIEW_ROUTINE_OFFSET,
    starter_dex_preview_patch_offset=None,
)

RED_VERSIONS = [
    RED_DE,
    RED_EN,
    RED_ES,
    RED_FR,
    RED_IT,
    RED_JP_V10,
    RED_JP_V11,
]
