from games.gen1.base import Gen1GameDefinition
from games.gen1.constants import (
    YELLOW_INTL_SPECIES_NAME_TABLE_OFFSET,
    YELLOW_JP_SPECIES_NAME_TABLE_OFFSET,
    INTL_STARTING_MONEY_PATCH_OFFSET,
)

YELLOW_DE = Gen1GameDefinition(
    name="POKéMON GELBE",
    internal_title="POKEMON YELAPSD",
    generation=1,
    language_code="D",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x61,
    global_checksum=0x66FB,
    species_name_table_offset=YELLOW_INTL_SPECIES_NAME_TABLE_OFFSET,
    intro_mon_offset=0x5EF0,
    starting_money_wram_offset=0xD34B,
    starting_money_routine_offset=0xF702,
    starting_money_middle_byte_offset=0xF706,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF70C,
    starting_pc_item_offset=0x5EB7,
)

YELLOW_EN = Gen1GameDefinition(
    name="POKéMON YELLOW",
    internal_title="POKEMON YELLOW",
    generation=1,
    language_code="E",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x97,
    global_checksum=0x047C,
    species_name_table_offset=YELLOW_INTL_SPECIES_NAME_TABLE_OFFSET,
    intro_mon_offset=0x5EDB,
    starting_money_wram_offset=0xD346,
    starting_money_routine_offset=0xF70D,
    starting_money_middle_byte_offset=0xF711,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF717,
    starting_pc_item_offset=0x5EA2,
)

YELLOW_ES = Gen1GameDefinition(
    name="POKéMON AMARILLA",
    internal_title="POKEMON YELAPSS",
    generation=1,
    language_code="S",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x52,
    global_checksum=0x5637,
    species_name_table_offset=YELLOW_INTL_SPECIES_NAME_TABLE_OFFSET,
    intro_mon_offset=0x5F22,
    starting_money_wram_offset=0xD34B,
    starting_money_routine_offset=0xF710,
    starting_money_middle_byte_offset=0xF714,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF71A,
    starting_pc_item_offset=0x5EE9,
)

YELLOW_FR = Gen1GameDefinition(
    name="POKéMON JAUNE",
    internal_title="POKEMON YELAPSF",
    generation=1,
    language_code="F",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x5F,
    global_checksum=0xB7C1,
    species_name_table_offset=YELLOW_INTL_SPECIES_NAME_TABLE_OFFSET,
    intro_mon_offset=0x5F64,
    starting_money_wram_offset=0xD34B,
    starting_money_routine_offset=0xF6FD,
    starting_money_middle_byte_offset=0xF701,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF707,
    starting_pc_item_offset=0x5F2B,
)

YELLOW_IT = Gen1GameDefinition(
    name="POKéMON GIALLA",
    internal_title="POKEMON YELAPSI",
    generation=1,
    language_code="I",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x5C,
    global_checksum=0x4E8F,
    species_name_table_offset=YELLOW_INTL_SPECIES_NAME_TABLE_OFFSET,
    intro_mon_offset=0x5F2A,
    starting_money_wram_offset=0xD34B,
    starting_money_routine_offset=0xF711,
    starting_money_middle_byte_offset=0xF715,
    starting_money_patch_offset=INTL_STARTING_MONEY_PATCH_OFFSET,
    starting_money_return_offset=0xF71B,
    starting_pc_item_offset=0x5EF1,
)

YELLOW_JP_10 = Gen1GameDefinition(
    name="ポケットモンスター ピカチュウ",
    internal_title="POKEMON YELLOW",
    generation=1,
    language_code="J",
    revision="v1.0",
    version_byte=0x00,
    header_checksum=0x20,
    global_checksum=0x9C29,
    species_name_table_offset=YELLOW_JP_SPECIES_NAME_TABLE_OFFSET,
    intro_mon_offset=0x5E3A,
    starting_money_wram_offset=0xD2CB,
    starting_money_routine_offset=0xFA11,
    starting_money_middle_byte_offset=0xFA15,
    starting_money_patch_offset=None,
    starting_money_return_offset=0xFA1B,
    starting_pc_item_offset=0x5E01,
)

YELLOW_JP_11 = Gen1GameDefinition(
    name="ポケットモンスター ピカチュウ",
    internal_title="POKEMON YELLOW",
    generation=1,
    language_code="J",
    revision="v1.1",
    version_byte=0x01,
    header_checksum=0x1F,
    global_checksum=0x8858,
    species_name_table_offset=YELLOW_JP_SPECIES_NAME_TABLE_OFFSET,
    intro_mon_offset=0x5E3A,
    starting_money_wram_offset=0xD2CB,
    starting_money_routine_offset=0xFA08,
    starting_money_middle_byte_offset=0xFA0C,
    starting_money_patch_offset=None,
    starting_money_return_offset=0xFA12,
    starting_pc_item_offset=0x5E01,
)

YELLOW_JP_12 = Gen1GameDefinition(
    name="ポケットモンスター ピカチュウ",
    internal_title="POKEMON YELLOW",
    generation=1,
    language_code="J",
    revision="v1.2",
    version_byte=0x02,
    header_checksum=0x1E,
    global_checksum=0xEDD9,
    species_name_table_offset=YELLOW_JP_SPECIES_NAME_TABLE_OFFSET,
    intro_mon_offset=0x5E3A,
    starting_money_wram_offset=0xD2CB,
    starting_money_routine_offset=0xFA08,
    starting_money_middle_byte_offset=0xFA0C,
    starting_money_patch_offset=None,
    starting_money_return_offset=0xFA12,
    starting_pc_item_offset=0x5E01,
)

YELLOW_JP_13 = Gen1GameDefinition(
    name="ポケットモンスター ピカチュウ",
    internal_title="POKEMON YELLOW",
    generation=1,
    language_code="J",
    revision="v1.3",
    version_byte=0x03,
    header_checksum=0x1D,
    global_checksum=0xD984,
    species_name_table_offset=YELLOW_JP_SPECIES_NAME_TABLE_OFFSET,
    intro_mon_offset=0x5E3A,
    starting_money_wram_offset=0xD2CB,
    starting_money_routine_offset=0xFA08,
    starting_money_middle_byte_offset=0xFA0C,
    starting_money_patch_offset=None,
    starting_money_return_offset=0xFA12,
    starting_pc_item_offset=0x5E01,
)

YELLOW_VERSIONS = [
    YELLOW_DE,
    YELLOW_EN,
    YELLOW_ES,
    YELLOW_FR,
    YELLOW_IT,
    YELLOW_JP_10,
    YELLOW_JP_11,
    YELLOW_JP_12,
    YELLOW_JP_13,
]
